spring.application.name=event-ticket-system
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/eventsdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update


